### ISSUE TITLE
Install from npm or GitHub

### ISSUE THREAD

**Issue by lukechilds** [jstrace/chart#10]
Just tried to publish a new version to npm but it's erroring because the module name in `package.json` is `chart` but on npm it's `ascii-chart`. Also just noticed in the readme it recommends installation via GitHub `npm install jstrace/chart`.

Is there a reason for this? Are you happy for me to change the `package.json` name to `ascii-chart`, publish to npm and update the readme installation section to reflect that?

**Comment by lukechilds** [comment]
@tj Just seen this: https://github.com/jstrace/chart/issues/2. What was the reason behind it?

**Comment by tj** [comment]
I just prefer avoiding npm these days, it's an extra thing to manage

**Comment by lukechilds** [comment]
So you wan't me to keep it as is?

Also, doesn't installing via git just install at the latest commit with no SemVer?

**Comment by tj** [comment]
Yeah people have to lock via the GIT SHA but that's not such a bad thing, your call though! Doesn't matter to me, I just like the Go-ish workflow of pushing to GH and not worrying about it

**Comment by lukechilds** [comment]
Interesting, I'll publish to npm just to keep it updated but I won't commit the package name changes to GitHub so everything will still work with `npm install jstrace/chart` & `require('chart')` as is.

You've got me thinking, tbh I think SemVer updates have hurt me more times than they've helped me.

**Comment by tj** [comment]
Personally I definitely prefer to err on the side of caution. If there's a bug of some kind in a module I'll notice it and bump anyway haha, I don't think I've ever had a bug I didn't notice get fixed magically by the semver range or something

**Comment by lukechilds** [comment]
Yup, `jsdom` recently did a "minor" SemVer update that completely broke one of my modules I use for mocking a browser environment in my tests. So then all my tests started failing on all my projects that used it. That was a fun day.

I've been pinning version numbers and keeping track of updates with Greenkeeper since: https://github.com/lukechilds/node-browser-environment/pull/4 worth checking out if you're doing any more node stuff in the future 👍
